name: Build and push the Docker image to ghcr.io

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        strategy:
            matrix:
                dockerfile:
                    - Dockerfile.api
                    - Dockerfile.www
                include:
                    - dockerfile: Dockerfile.api
                      context: .
                      image_suffix: api
                    - dockerfile: Dockerfile.www
                      context: .
                      image_suffix: www

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ${{ matrix.context }}
                  file: ${{ matrix.dockerfile }}
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image_suffix }}:latest
